services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: ./app/strelka_ui
        - action: rebuild
          path: ./ui/src
    container_name: strelka-ui-webapp
    ports:
      - "8080:8080"
    depends_on:
      - postgresdb
    environment:
      DATABASE_HOST: postgresdb
      DATABASE_NAME: strelka_ui
      DATABASE_PASSWORD: postgres
      DATABASE_USERNAME: postgres
      STRELKA_CERT: /certs/strelka_cert.crt
      CA_CERT_PATH: /tgt-ca-bundle.crt
      ENV: dev
    env_file: ./app/strelka_ui/.env
    volumes:
      - ./certs:/certs

  postgresdb:
    image: hub.docker.target.com/bitnami/postgresql:17
    container_name: strelka-ui-postgresdb
    environment:
      POSTGRESQL_DATABASE: strelka_ui
      POSTGRESQL_PASSWORD: postgres
      POSTGRESQL_USERNAME: postgres
    ports:
      - "5432:5432"
    volumes:
      - data17:/bitnami/postgresql

volumes:
  data17:

